studentProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
]

students/urls.py
from django.urls import path
from . import views


app_name = 'students'
urlpatterns = [
    path('reg/', views.regStudent, name = 'reg'),
    path('regCon/', views.regConStudent, name = 'regCon'),
    path('all/', views.reaStudentAll, name = 'stuAll'),
    path('<str:name>/detail/', views.detailStudent, name = 'stuDetail'),
    path('<str:name>/modify/', views.modifyStudentOne, name = 'stuModify'),
    path('modifyCon/', views.modifyConStudent, name = 'modifyCon'),
    path('<str:name>/delete/', views.delConStudent, name = 'stuDel'),
]

students/models.py
from django.db import models

class Student(models.Model):
    s_name = models.CharField(max_length = 100)
    s_major = models.CharField(max_length = 100)
    s_age = models.IntegerField(default = 0)
    s_grade = models.IntegerField(default = 0)
    s_gender = models.CharField(max_length = 30)
    
    def __str__(self):
        return self.s_name
    

students/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from students.models import Student

def regStudent(request):
    return render(request, 'students/registerStudent.html')

def regConStudent(request):
    name = request.POST['name']
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']
    
    queryStr = Student(s_name=name, s_major=major, s_age=age, s_grade=grade, s_gender=gender)
    queryStr.save()
    
    return HttpResponseRedirect(reverse('students:stuAll'))

def reaStudentAll(request):
    queryStr = Student.objects.all()
    context = {'student_list' : queryStr}
    return render(request, 'students/readStudentsAll.html', context)

def detailStudent(request, name):
    queryStr = Student.objects.get(s_name=name)
    context = {'student_info' : queryStr}
    return render(request, 'students/detailStudent.html', context )

def modifyStudentOne(request, name):
    queryStr = Student.objects.get(s_name=name)
    context = {'student_info' : queryStr}
    return render(request, 'students/modifyStudentOne.html', context)

def modifyConStudent(request):
    name = request.POST['name']
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']
    
    queryStr = Student.objects.get(s_name = name)
    queryStr.s_name = name
    queryStr.s_major = major
    queryStr.s_age = age
    queryStr.s_grade = grade
    queryStr.s_gender = gender
    
    queryStr.save()
    
    return HttpResponseRedirect(reverse('students:stuAll'))

def delConStudent(request, name):
    queryStr = Student.objects.get(s_name = name)
    queryStr.delete()
    
    return HttpResponseRedirect(reverse('students:stuAll'))

students/templates/students/detailStudent.html
<!DECTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html"; charset=UTF-8>
         <title>Title</title>
    </head>
    
    <body>
        <p>Read Student</p>
        
        {% if student_info %}
            이름 : {{student_info.s_name}}<br>
            전공 : {{student_info.s_major}}<br>
            나이 : {{student_info.s_age}}<br>
            학년 : {{student_info.s_grade}}<br>
            성별 : {{student_info.s_gender}}<br>
        {% else %}
            <p>Student : 0</p>
        {% endif %}
        
        <br>
        <a href = "{% url 'students:stuModify' student_info.s_name %}">수정</a>
        <a href = "{% url 'students:stuDel' student_info.s_name %}">삭제</a>
        <a href = "{% url 'students:stuAll' %}">학생리스트</a>
        <a href = "{% url 'students:reg' %}">신규학생등록</a>
        
    </body>
</html>

students/templates/students/modifyStudentOne.html
<!DECTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html"; charset=UTF-8>
         <title>Title</title>
    </head>
    
    <body>
        <p>Modify Student</p>
        
        {% if student_info %}
            <form action="{% url 'students:modifyCon' %}" method="post">
                {% csrf_token %}
                이름 : {{student_info.s_name}} 
                <input type="hidden" name="name" value="{{student_info.s_name}}"><br>
                전공 : <input type="text" name="major" value="{{student_info.s_major}}"><br>
                나이 : <input type="text" name="age" value="{{student_info.s_age}}"><br>
                학년 : <input type="text" name="grade" value="{{student_info.s_grade}}"><br>
                성별 : <input type="text" name="gender" value="{{student_info.s_gender}}"><br>
                <input type="submit" name="Modify">
            </form>
        {% else %}
            <p>Student Error</p>
        {% endif %}
        
    </body>
</html>

students/templates/students/readStudentsAll.html
<!DECTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html"; charset=UTF-8>
         <title>Title</title>
    </head>
    
    <body>
        <p>Register Student</p>
        
        {% if student_list %}
            <ol>
                {% for s in student_list %}
                    <li>
                        <a href = "{% url 'students:stuDetail' s.s_name %}">{{s.s_name}}</a>
                        <a href = "{% url 'students:stuModify' s.s_name %}">수정</a>
                        <a href = "{% url 'students:stuDel' s.s_name %}">삭제</a>
                    </li>
                 {% endfor %}
            </ol>
        {% else %}
            <p>Student : 0</p>
        {% endif %}
        
        <br>
        <a href = "{% url 'students:reg' %}">신규학생등록</a>
        
    </body>
</html>

students/templates/students/registerStudent.html
<!DECTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html"; charset=UTF-8>
         <title>Title</title>
    </head>
    
    <body>
        <p>Register Student</p>
        
        <form action="{% url 'students:regCon' %}" method="post">
        {% csrf_token %}
            이름 : <input type="text" name="name"><br>
            전공 : <input type="text" name="major"><br>
            나이 : <input type="text" name="age"><br>
            학년 : <input type="text" name="grade"><br>
            성별 : <input type="text" name="gender"><br>
            <input type="submit" name="Register">
        </form>
    </body>
</html>